name: Stardust CI/CD

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: 
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Verify build
        run: |
          uv build
          uv pip install dist/*.whl
          
      - name: Run tests
        run: uv run pytest
  
      - name: Publish Python 🐍 distribution 📦 to PyPI and TestPyPI
        if: startsWith(github.ref, 'refs/tags/')
        env:          
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          # Extract version from tag
          VERSION=${GITHUB_REF#refs/tags/v}
          # Verify package version matches tag
          grep "version = \"$VERSION\"" pyproject.toml || (echo "Version mismatch" && exit 1)
          uv build
          uv publish
