name: Stardust CI/CD

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    name: Python ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pipenv'

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

      - name: Install dependencies
        run: pipenv install --dev --python '${{ steps.setup-python.outputs.python-path }}'

      - name: Run tests
        run: |
          pipenv run test

      - name: Publish Python 🐍 distribution 📦 to PyPI and TestPyPI
        if: startsWith(github.ref, 'refs/tags/')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          pipenv run package
          pipenv run publish
