name: Publish to PyPI
on:
  release:
    types: [published]

jobs:
  pypi_release:
    name: Builds Using Poetry and Publishes to PyPI
    runs-on: ubuntu-latest
    environment: PyPi
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Set up Python 3.10
        run: uv python install 3.10
      - name: Install the project
        run: uv sync --all-extras --dev
      - run: uv run pytest
      - run: uv build
      - name: Publish to Test PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: uv publish
